### PR TITLE
Remove funding.yml

### PR DESCRIPTION
**Pull request by tiqwab**
A new repository generated from this template still contains `.github/funding.yml` with your information.
I am not familiar with the detail of the funding file mechanism, but you can remove it from this repository because you manage it in your `.github` repository?

### CODE REVIEW

**Comment by fregante** [comment]
> because you manage it in your `.github` repository

Correct, but the file exists here because it includes funding for the 2 maintainers.

Unfortunately there's no straightforward way to exclude files when a template is "used": https://github.community/t/can-you-ignore-files-folders-when-making-a-repo-from-a-template/3279

The page above includes a workflow example that cleans up the repo on creation. If you submit a PR with such workflow I can merge it.

**Comment by notlmn** [comment]
> Correct, but the file exists here because it includes funding for the 2 maintainers.

I would say we can go ahead with this. I tried removing almost all funding references of mine on GitHub recently as I _mostly_ don't work on OSS (like once a month now) anymore because I have a relatively well paying day job that takes most of my time (that helps me support fregante@, thanks!).

GitHub ideally should have a way to exclude some files for cloning templates though, but I guess that's not how Git works.

**Comment by tiqwab** [comment]
Thank you for explaining context about it.

So if you don't mind, I will send another pull request to implement a cleanup workflow. I think it is better because we might want to do more things to initialize a created repository in the future :).

**Comment by tiqwab** [comment]
Another pull request https://github.com/fregante/browser-extension-template/pull/81 is created, so close it.

**Pull request closed without merging**
