### PR TITLE
Use Manifest v3

### LINKED ISSUE #55: Manifest v3
I've just started experimenting with browser extensions and came across this from [OctoPrint - Open in Bundle Viewer](https://github.com/OctoPrint/Open-In-Bundle-Viewer) which was based on your template.

Do you have plans to update this template or rather recreate this template for version 3 of the manifest.json?

[Chrome Developers - Intro to Manifest v3](https://developer.chrome.com/docs/extensions/mv3/intro/)

### PR DESCRIPTION
**Pull request by fregante**
- Closes #55 

This drops support for Firefox 🤷‍♂️

### CODE REVIEW

**Comment by fregante** [comment]
Blocked by:

- [ ] https://github.com/parcel-bundler/parcel/issues/7952

**Comment by notlmn** [comment]
My bad, bad mouse clicks.

> This drops support for Firefox 🤷‍♂️

Is there a tool out there that does manifest v2 generation from a manifest v3 configuration? That should still help with having two deployments to different stores.

**Comment by fregante** [comment]
Not that I know of. Currently it's impossible to use this template for Chrome so it's best to make the switch regardless of Firefox support (which is a small percentage of users)

**Comment by Stvad** [comment]
Firefox user here 😛 . It'd make me sad to see FF support dropped leaving me with no options for starting new extensions 🙁.  I think having 2 manifests and 2 separate build commands that use those as entry points can be an option?  

what @notlmn mentions (generating one version from another, or generating both versions from a common template) would be ideal, but just having 2 manifests should be an easy option to start with?

**Comment by fregante** [comment]
Indeed you can do that after using the template, but here it would mean duplicating every build command *and* the manifest itself, it's a mess. I assume Firefox is only a couple of months away from allowing MV3

**Comment by Stvad** [comment]
Aren't templates meant to make life with messes easier? 😅

**Comment by Stvad** [comment]
Also, I think not all commands, but just the `build` one?

**Comment by fregante** [comment]
> Aren't templates meant to make life with messes easier? 😅

True, but you're assuming that what you're suggesting is easier, which it isn't. For a starter, `parcel` only works if the file is named exactly `manifest.json`. So if we have:

- source/manifest.json
- source/manifest-firefox.json

The second run gets:

```
❯ nr build
✨ Built in 550ms

distribution/manifest-firefox.js    734 B    106ms
```

So what's the alternative? 

- Moving manifest for Firefox in another directory? Then its paths will all need to be updated too (assuming that works without pain)
- Duplicating the whole source folder? That'd be a terrible template.

At this point, if Firefox support is paramount, then I suggest going with a Webpack-based build like https://github.com/aeksco/react-typescript-web-extension-starter

**Comment by 101arrowz** [comment]
We've fixed `browser_specific_settings` upstream, FF support should now still be possible from the same manifest. Unfortunately `web_accessible_resources` aren't completely fixed yet but basic functionality should still work.

**Comment by Stvad** [comment]
@fregante will experiment with different folders for manifest approach which seems like it can be ok and let you know how it goes!

**Comment by fregante** [comment]
@101arrowz thank you for the comment! From my understanding the latest version is broken for content scripts?

> FF support should now still be possible from the same manifest. 

FF completely fails to load MV3 extensions, this is not a Parcel issue unfortunately; `browser_specific_settings` was a relatively minor issue

**Comment by Stvad** [comment]
@fregante double-folder approach works btw, see manifest and package.json changes in https://github.com/transclude-me/extension/commit/78b529ef1af32ba076b3b852f21145f48dfdb1b9

**Comment by Stvad** [comment]
I'm hitting a weird bug with bundling though. It does not seem to be related to the double folder approach, but started happenign to me after 2.5 upgrade: https://github.com/parcel-bundler/parcel/issues/8071

**Comment by aspiers** [comment]
> @fregante double-folder approach works btw, see manifest and package.json changes in [transclude-me/extension@78b529e](https://github.com/transclude-me/extension/commit/78b529ef1af32ba076b3b852f21145f48dfdb1b9)

This commit appears to mix adding the double-folder approach together with a bunch of changes specific to your extension - right?  Any chance you could summarise just the generic double-folder changes needed?

**Comment by Stvad** [comment]
That’s correct. Summary is:
- create 2 manifests
- Update paths in them
- add commands in package.json to deal with that
- beware the path change for the resources used via runtime.getURL (https://github.com/transclude-me/extension/commit/78b529ef1af32ba076b3b852f21145f48dfdb1b9#diff-ebd593fb607241eb184425ae1ae5b98a4c44f5ffc0355b2d0e485ad423caa29bR12)

**Comment by fregante** [comment]
Please continue in https://github.com/fregante/browser-extension-template/issues/78

**Pull request merged**
