### PR TITLE
Revert "Update dependencies"

### LINKED ISSUE #65: Issue with using import in content scripts
The default template is throwing this error `SyntaxError: import declarations may only appear at top level of a module` when attempting to access a page that should trigger the content.js script. Upon searching a bit, I found that the issue was a limitation of the files that can be included through content_scripts due to needing the type="module" attribute needing to be set on the script https://stackoverflow.com/questions/48104433/how-to-import-es6-modules-in-content-script-for-chrome-extension. Is there a version of this template that has this working properly? Does a transpolar need to be configured in order to maintain syntax when dealing with content?

### PR DESCRIPTION
**Pull request by fregante**
Reverts fregante/browser-extension-template#64

Temporarily fixes https://github.com/fregante/browser-extension-template/issues/65

I don't have time to look into the issue right now, but I assume this is the cause since Parcel likes to make breaking changes in every release

### CODE REVIEW

**Comment by fregante** [comment]
cc @humphd

**Comment by humphd** [comment]
Ah, sucks.  Sorry for the churn.

**Comment by fregante** [comment]
No worries, this is Parcel's fault. I assume semver minor updates don't break stuff, but Parcel essentially does not care about semver.

**Comment by humphd** [comment]
I don't think it's that, so much as the switch to the new compiler, and lots of edge cases being found in the ecosystem.  I file lots of bugs with them and they fix.

**Comment by fregante** [comment]
No, I had the same exact error before because they made things more strict and therefore break the build. Probably they extended the strictness to the content script entry point and it's possible that it won't let us use `import` in it unless I create an additional file. 

If you have time to report this actually it would be great

**Comment by fregante** [comment]
uhm, I found the time to try it and it actually works. The report was likely incorrect… I reverted my reversion 😃

**Pull request merged**
