### PR TITLE
Add release notes action

### LINKED ISSUE #37: Create release notes using actions
With https://github.com/notlmn/release-with-changelog

Follows https://github.com/notlmn/release-with-changelog/pull/3 or https://github.com/sindresorhus/refined-github/pull/3421

### PR DESCRIPTION
**Pull request by notlmn**
Closes #37.

Using https://github.com/notlmn/release-with-changelog for creating a new release for every tag pushed.

Also for testing https://github.com/notlmn/release-with-changelog/pull/3

### CODE REVIEW

**Comment by notlmn** [comment]
@fregante, let's review this and get it merged ASAP for testing

**Comment by fregante** [comment]
This is exactly what was PR'd on RG and github-url-detection; it won't work because releases are created by GHA itself. The workflow needs to be part of `deployment / Build` itself, right after the tag creation: https://github.com/notlmn/browser-extension-template/blob/master/.github/workflows/deployment.yml#L22

**Comment by notlmn** [comment]
> This is exactly what was PR'd on RG and github-url-detection; it won't work because releases are created by GHA itself. The workflow needs to be part of `deployment / Build` itself, right after the tag creation: [https://github.com/notlmn/browser-extension-template/blob/master/.github/workflows/deployment.yml#L22](https://github.com/notlmn/browser-extension-template/blob/master/.github/workflows/deployment.yml?rgh-link-date=2020-09-08T18%3A02%3A52Z#L22)

I'm losing it!

Also wouldn't we be dropping manual tag pushes in that case?

**Comment by fregante** [comment]
Ideally we’d support both, but manual tag pushes require a bit of (undocumented) setup and it’s not particularly worth it since manual deployment is available on GitHub with a click. Let’s just support fully automatic deployment. 

Also if you’re just creating tags locally manually, you already have tools to also create the release, like vercel/release

**Review by fregante — APPROVED** [review]

**Comment by notlmn** [comment]
Well, that works after manual workflow trigger 🎉

Release: https://github.com/notlmn/browser-extension-template/releases/tag/20.9.9.1450
GHA Run: https://github.com/notlmn/browser-extension-template/actions/runs/246486785

**Comment by fregante** [comment]
Excellent!

**Pull request merged**
